### ISSUE TITLE
Mayhem Mode and Anointed Items

### ISSUE THREAD

**Issue by ensiform** [apocalyptech/bl3-cli-saveedit#4] opened 2020-04-16 14:10 UTC
Using this tool to activate Mayhem mode before completion of story will not result in Anointed Items dropping FYI. Even setting to level 57 as well.

Not sure if there is some tick in the save that enables it as well as mayhem mode I will update this when I complete the story on my character I tested this with.

**Comment by apocalyptech** [comment] 2020-04-16 14:28
Huh, thanks for the info - I'll have to run some tests and dig into data.  I've been using some modding-type shenanigans to unlock anointments globally so I'd not noticed.  Could be that I'm missing an extra Challenge or something; GBX tends to use those for a lot of game status info.

Thanks again, I'll definitely dig into it today!

**Comment by mightydanp** [comment] 2020-04-16 15:48
Anointed Items will not drop unless you have true volt hunter mode unlocked for that character

**Comment by mightydanp** [comment] 2020-04-16 15:48
If you want it to drop when you make a character enable it and then when you start the game chose regular volt hunter mode

**Comment by apocalyptech** [comment] 2020-04-16 19:04
Okay, so I don't think I'm able to reproduce this, actually -- it seems to be working fine for me.  Here's the saves that I was using:

[saves.zip](https://github.com/apocalyptech/bl3-cli-saveedit/files/4489262/saves.zip)

`no_mayhem_01-before_finishing.sav` and `no_mayhem_02-after_finishing.sav` are from before and after finishing the story, with a save that's never had Mayhem mode edited into it.  `m1_01-before_finishing.sav` and `m1_02-after_finishing.sav` are the same, but the "before" save has Mayhem 1 activated via the editor.  In both cases, I've got anointed items showing up in the vending machines in Sanctuary, using the "after" versions.

Could you maybe attach a savegame, if you've got one which is displaying the problem?  Thx!

**Comment by apocalyptech** [comment] 2020-04-16 19:07
Oh, y'know, I misread your original report -- I thought you meant that you weren't seeing anointments *after* you completed the story, when you'd edited in Mayhem mode beforehand.  So yeah, @mightydanp is exactly right -- you need to unlock THVM in order to get anointments to start dropping.  `--unlock tvhm` should do the trick for you.  I suppose I could add that to the README.
Thanks for the report!  I'm closing this out, but if I've misunderstood, definitely let me know and I can take a look.

**Closed by apocalyptech** 2020-04-16 19:07 UTC
